name: LightAntiCheat
version: ${project.version}
main: pagofr.lightanticheat.LightAntiCheat
api-version: 1.17
author: Pagofr
description: Updated Version of Veksters LightAntiCheat
website: https://github.com/Pagofr/PGLightAntiCheat
softdepend:
  - Geyser-Spigot
  - floodgate
  - ViaVersion
  - ProtocolSupport
commands:
  lightanticheat:
    aliases: lac
permissions:
  lightanticheat.reload:
    default: op
    description: Allow "/lightanticheat reload"
  lightanticheat.bypass:
    default: op
    description: Bypasse all checks
  lightanticheat.alerts.*:
    default: op
    description: Show all notifications wildcard
    children:
      lightanticheat.alerts.punishment: true
      lightanticheat.alerts.warn: true
      lightanticheat.alerts.debug: true
      lightanticheat.alerts.update: true
  lightanticheat.alerts.punishment:
    default: false
    description: Show punishment notifications
  lightanticheat.alerts.warn:
    default: false
    description: Show warn notifications
  lightanticheat.alerts.debug:
    default: false
    description: Show debug notifications
  lightanticheat.alerts.update:
    default: false
    description: Show update notifications
